
const date = new Date();

// 0 scheduled
// 1 Requests
// 2 Upcoming
// 3 Completed



// 0 Payment Pending
// 1 Payment Received

export const interviewerJsonList = [
    
    {
        id : 'interviewer_001',
        job_title : 'IOS and Android Developer',
        company : 'Info Systems Inc.',
        location : 'Jacksonvilla FI, USA',
        assessment : '2 Way Video Interview',
        duration_in_minute : 30,
        charge : 75,
        currency : 'USD',
        currency_sign : '$',
        date_time : date,
        days_ago : 1,
        status : 0,
        bid_min : 50,
        bid_max : 100,
        total_bids : 10,
        placed_bids : 4,
        payment_status : 0,
        
    },
    {
        id : 'interviewer_002',
        job_title : 'Data Analyst',
        company : 'Info Systems Inc.',
        location : 'Jacksonvilla FI, USA',
        assessment : '2 Way Video Interview',
        duration_in_minute : 30,
        charge : 75,
        currency : 'USD',
        currency_sign : '$',
        date_time : date,
        days_ago : 1,
        status : 0,
        bid_min : 50,
        bid_max : 100,
        total_bids : 10,
        placed_bids : 4,
        payment_status : 0,
    },
    {
        id : 'interviewer_003',
        job_title : 'Graphic Designer',
        company : 'Info Systems Inc.',
        location : 'Jacksonvilla FI, USA',
        assessment : '2 Way Video Interview',
        duration_in_minute : 30,
        charge : 75,
        currency : 'USD',
        currency_sign : '$',
        date_time : date,
        days_ago : 1,
        status : 1,
        bid_min : 50,
        bid_max : 100,
        total_bids : 10,
        placed_bids : 4,
        payment_status : 0,
    },
    {
        id : 'interviewer_004',
        job_title : 'IOS and Android Developer',
        company : 'Info Systems Inc.',
        location : 'Jacksonvilla FI, USA',
        assessment : '2 Way Video Interview',
        duration_in_minute : 30,
        charge : 75,
        currency : 'USD',
        currency_sign : '$',
        date_time : date,
        days_ago : 1,
        status : 1,
        bid_min : 50,
        bid_max : 100,
        total_bids : 10,
        placed_bids : 4,
        payment_status : 0,
    },
    {
        id : 'interviewer_005',
        job_title : 'Backend Developer',
        company : 'Info Systems Inc.',
        location : 'Jacksonvilla FI, USA',
        assessment : '2 Way Video Interview',
        duration_in_minute : 30,
        charge : 75,
        currency : 'USD',
        currency_sign : '$',
        date_time : date,
        days_ago : 1,
        status : 2,
        bid_min : 50,
        bid_max : 100,
        total_bids : 10,
        placed_bids : 4,
        payment_status : 0,
    },
    {
        id : 'interviewer_006',
        job_title : 'IOS and Android Developer',
        company : 'Info Systems Inc.',
        location : 'Jacksonvilla FI, USA',
        assessment : '2 Way Video Interview',
        duration_in_minute : 30,
        charge : 75,
        currency : 'USD',
        currency_sign : '$',
        date_time : date,
        days_ago : 1,
        status : 2,
        bid_min : 50,
        bid_max : 100,
        total_bids : 10,
        placed_bids : 4,
        payment_status : 0,
    },
    {
        id : 'interviewer_007',
        job_title : 'Data Administrator',
        company : 'Info Systems Inc.',
        location : 'Jacksonvilla FI, USA',
        assessment : '2 Way Video Interview',
        duration_in_minute : 30,
        charge : 75,
        currency : 'USD',
        currency_sign : '$',
        date_time : date,
        days_ago : 1,
        status : 3,
        bid_min : 50,
        bid_max : 100,
        total_bids : 10,
        placed_bids : 4,
        payment_status : 0,
        
    },
    {
        id : 'interviewer_008',
        job_title : 'IOS and Android Developer',
        company : 'Info Systems Inc.',
        location : 'Jacksonvilla FI, USA',
        assessment : '2 Way Video Interview',
        duration_in_minute : 30,
        charge : 75,
        currency : 'USD',
        currency_sign : '$',
        date_time : date,
        days_ago : 1,
        status : 3,
        bid_min : 50,
        bid_max : 100,
        total_bids : 10,
        placed_bids : 4,
        payment_status : 1,
    },
]