export const USER_DATA = 'USER_DATA'
export const LOGOUT = 'LOGOUT'

export const CURRENT_BOTTOM_TAB = 'CURRENT_BOTTOM_TAB'
export const EXTRA_DATA = 'EXTRA_DATA'
export const USER_PREFS = 'USER_PREFS'


// export const JOB_FILTERS_LIST = 'JOB_FILTERS_LIST'
// export const JOB_FILTERS_LIST_EXTRA_DATA = 'JOB_FILTERS_LIST_EXTRA_DATA'
// export const SORTS_LIST = 'SORTS_LIST'




// //common actions
// export const COMMON_DATA = 'COMMON_DATA'

// //home actions
export const MY_JOBS = 'MY_JOBS'
export const MATCHED_JOBS = 'MATCHED_JOBS'
export const RTR_JOBS = 'RTR_JOBS'
export const APPLIED_JOBS = 'APPLIED_JOBS'
export const FAV_JOBS = 'FAV_JOBS'

export const MY_TODOS = 'MY_TODOS'
export const UPCOMING_INTERVIEWS = 'UPCOMING_INTERVIEWS'


export const MY_LEARNINGS = 'MY_LEARNINGS'


export const ALL_TODOS = 'ALL_TODOS';
export const TODOS_RTR = 'TODOS_RTR';
export const TODOS_ASSESSMENTS = 'TODOS_ASSESSMENTS';
export const TODOS_INTERVIEW_SCHEDULING = 'TODOS_INTERVIEW_SCHEDULING'




// export const RESUME_TEXT = 'RESUME_TEXT'


// export const USER_SKILLS_LIST = 'USER_SKILLS_LIST'



// // settings Actions
// export const IS_PHONE_ACTIVE = 'IS_PHONE_ACTIVE'
// export const IS_EMAIL_ACTIVE = 'IS_EMAIL_ACTIVE'
// export const IS_CERTIFICATE_ACTIVE = 'IS_CERTIFICATE_ACTIVE'
// export const IS_WORK_EXPERIENCE_ACTIVE = 'IS_WORK_EXPERIENCE_ACTIVE'
// export const IS_EDUCATION_ACTIVE = 'IS_EDUCATION_ACTIVE'
// export const IS_VIDEO_INTERVIEW_ACTIVE = 'IS_VIDEO_INTERVIEW_ACTIVE'
// export const IS_LEARNING_ACTIVE = 'IS_LEARNING_ACTIVE'


// //Profile Actions

export const PROFILE_IMAGE = 'PROFILE_IMAGE'
export const PROFILE_PERSONAL_INFO = 'PROFILE_PERSONAL_INFO'
export const PROFILE_SOCIAL_MEDIA = 'PROFILE_SOCIAL_MEDIA'
export const PROFILE_STORY = 'PROFILE_STORY'
export const PROFILE_SKILLS = 'PROFILE_SKILLS'
export const PROFILE_EDUCATION = 'PROFILE_EDUCATION'
export const PROFILE_EXPERIENCES = 'PROFILE_EXPERIENCES'
export const PROFILE_CERTIFICATES = 'PROFILE_CERTIFICATES'
export const PROFILE_LICENSES = 'PROFILE_LICENSES'
export const PROFILE_LANGUAGES = 'PROFILE_LANGUAGES'
export const PROFILE_CUSTOM_SECTIONS = 'PROFILE_CUSTOM_SECTIONS'
export const PROFILE_AWARDS_AND_HONORS = 'PROFILE_AWARDS_AND_HONORS'
// export const PROFILE_INTERESTS = 'PROFILE_INTERESTS'
// export const PROFILE_PROJECTS = 'PROFILE_PROJECTS'
// export const PROFILE_REFERENCES = 'PROFILE_REFERENCES'
// export const PROFILE_SIGNATURE = 'PROFILE_SIGNATURE'
// export const PROFILE_ACTIVITY = 'PROFILE_ACTIVITY'
export const PREFERENCES = 'PREFERENCES'


// //Create Resume actions
// // export const RESUME_EDUCATION = 'RESUME_EDUCATION'
// // export const RESUME_EXPERIENCE = 'RESUME_EXPERIENCE'
// // export const RESUME_INTEREST = 'RESUME_INTEREST'
// // export const RESUME_PREFERENCES = 'RESUME_PREFERENCES'
// // export const RESUME_SKILLS = 'RESUME_SKILLS'
// // export const RESUME_LANGUAGES = 'RESUME_LANGUAGES'
// // export const RESUME_PROJECTS = 'RESUME_PROJECTS'
// // export const RESUME_PERSONAL_INFO = 'RESUME_PERSONAL_INFO'
// // export const RESUME_OBJECTIVE = 'RESUME_OBJECTIVE'
// // export const RESUME_ACHIEVEMENTS = 'RESUME_ACHIEVEMENTS'
// // export const RESUME_PUBLICATIONS = 'RESUME_PUBLICATIONS'
// // export const RESUME_ACTIVITIES = 'RESUME_ACTIVITIES'
// // export const RESUME_SIGNATURE = 'RESUME_SIGNATURE'
// // export const RESUME_CERTIFICATES = 'RESUME_CERTIFICATES'
// // export const RESUME_LICENSES = 'RESUME_LICENSES'

// // export const RESUME_CUSTOM_SECTIONS_LIST = 'RESUME_CUSTOM_SECTIONS_LIST'
// // export const UPDATE_CUSTOM_SECTION_EXTRA_DATA = 'UPDATE_CUSTOM_SECTION_EXTRA_DATA'

// // export const VIDEO_RESUMES_WITH_SCRIPT_LIST = 'VIDEO_RESUMES_WITH_SCRIPT_LIST'

export const RESUME_LIST = 'RESUME_LIST'
export const RESUME_VIEW_FLAGS = 'RESUME_VIEW_FLAGS'
// 


// //Interview Actions
export const INTERVIEWS_LIST = 'INTERVIEWS_LIST'
export const FAQS = 'FAQS'
export const ASSESSMENTS_LIST = 'ASSESSMENTS_LIST'
// export const MCQ_QUESTIONS_LIST = 'MCQ_QUESTIONS_LIST'
// export const VIDEO_QUESTIONS_LIST = 'VIDEO_QUESTIONS_LIST'


// //Learning Actions
export const TOVUTI_USER_ID = 'TOVUTI_USER_ID'
export const LEARN_LIST = 'LEARN_LIST'


// //Notifications Actions
// export const REQUEST_NOTIFICATIONS_LIST = 'REQUEST_NOTIFICATIONS_LIST'
// export const STATUS_NOTIFICATIONS_LIST = 'STATUS_NOTIFICATIONS_LIST'

// //Referral Actions
// export const REFERRALS_LIST = 'REFERRALS_LIST'



// //Interviewer Actions
// // export const APPLIED_SKILLS_FOR_INTERVIEWERS_LIST = 'APPLIED_SKILLS_FOR_INTERVIEWERS_LIST'
// export const APPLIED_AS_INTERVIEWER_LIST = 'APPLIED_AS_INTERVIEWER_LIST'
// export const INTERVIEWS_AS_INTERVIEWER = 'INTERVIEWS_AS_INTERVIEWER'



// //Request Jobs List
// export const REQUESTED_JOBS_LIST = 'REQUESTED_JOBS_LIST'


// //Payments Actions
// export const BANK_AND_CARD_LIST = 'BANK_AND_CARD_LIST'

